#!/usr/bin/env bash
# Configures a server with nginx

sudo apt-get upgrade
sudo apt-get install nginx
sudo nfw allow 'Nginx HTTP'
touch text
echo 'Hello World!' > text
sudo cp text /var/www/html/index.nginx-debian.html
rm text
