#!/usr/bin/env bash
# Configures a Nginx server with a 301 moved permanently

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
