#!/usr/bin/env bash
# Configures a Nginx server to have a custom 404 page

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
CUSTOM_404="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
HTTP_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "30i $CUSTOM_404" /etc/nginx/sites-available/default

sudo sed -i "29i $HTTP_HEADER" /etc/nginx/sites-available/default

sudo service nginx start
sudo service nginx reload
