#!/usr/bin/env bash
#Displays property of a file named "school"

file="school"

if [ -e $file ]
then
	echo "school file exists"
	if [ -s $file ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exists"
fi

if [ -f $file ]
then
	echo "school is a regular file"
fi
