#!/usr/bin/env bash
# Configures a server to block all incoming traffic
# Allows incoming traffic on port 22, 443 and 80

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny imcoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
